### PR TITLE
Fix field not restored if active

### LINKED ISSUE #1628: editor does not refresh active field after note undone
When changes are made to a field, and the user uses Edit>Undo, the note is reverted to its previous state in the database, but the current field text remains. This may cause the user to think the undo hasn't been applied, and may cause the new text to be saved again if any keys are pressed in that field.

### PR DESCRIPTION
**Pull request by hgiesel**
Fixes #1628, alternative for #1636.

@hikaru-y Sorry for picking up all those issues after you already started working on them. I've never had notifications turned for open issues on the anki repo, which I just turned on. As I just wrote the editor code, I know when something is more of a bug of an existing function (in this case `focusField`), rather than a missing feature.

### CODE REVIEW

File: ts/editor/EditingArea.svelte [hunk 1]
```diff
@@ -8,10 +8,17 @@ License: GNU AGPL, version 3 or later; http://www.gnu.org/licenses/agpl.html
...
         readonly name: string;
+        focusable: boolean;
+        /**
+         * The reaction to a user-initiated focus, e.g. by clicking on the
+         * handle, or clicking Tab.
+         */
         focus(): void;
+        /**
+         * Behaves similar to a refresh, e.g. sync with content, put the caret
+         * into a neutral position, a/o undo selections.
```
Comment (dae) [inline ts/editor/EditingArea.svelte:19]: a/o?

**Comment by dae** [comment]
@hikaru-y sorry for the duplicated effort here - any objections to me merging this approach?

**Comment by hikaru-y** [comment]
@hgiesel @dae No worries!

@dae No objections from me.
