### PR TITLE
Fix/disable FSRS short-term scheduler if w[17] or w[18] is zero

### LINKED ISSUE #3782: Disable the FSRS short-term scheduler if w[17] or w[18] is zero
If w[17] OR w[18] is zero, disable the FSRS short-term scheduler because FSRS won't be able to increase the stability with short-term reviews.

Inspired by https://forums.ankiweb.net/t/fsrs-5-1d-scheduling-and-learning-steps/50242/73

_Originally posted by @user1823 in https://github.com/ankitects/anki/issues/3496#issuecomment-2410867005_

This is even more important after https://github.com/ankitects/anki/pull/3742 because the optimizer will make w[17] and w[18] equal to zero for more users now.

### PR DESCRIPTION
**Pull request by L-M-Sherlock**
close #3782

### CODE REVIEW

File: rslib/src/scheduler/states/review.rs [hunk 1]
```diff
@@ -124,7 +124,8 @@ impl ReviewState {
                 review: again_review,
             }
             .into()
-        } else if (ctx.fsrs_short_term_with_steps_enabled || ctx.relearn_steps.is_empty())
+        } else if (ctx.fsrs_enable_short_term && ctx.fsrs_short_term_with_steps_enabled
```
Comment (user1823) [inline rslib/src/scheduler/states/review.rs:127]: Parenthesis seem to be missing here. It should be 

```rs
        } else if (ctx.fsrs_enable_short_term && (ctx.fsrs_short_term_with_steps_enabled
            || ctx.relearn_steps.is_empty()))
```

**Comment by user1823** [comment]
Using the name `fsrs_allow_short_term` instead of `fsrs_enable_short_term` might be less confusing.

File: rslib/src/scheduler/states/review.rs (hunk 1 above)
Comment (L-M-Sherlock) [reply rslib/src/scheduler/states/review.rs]: fixed

**Comment by dae** [comment]
Thank you both!
