### PR TITLE
Fix/Invalid memory states in simulator after parameters changed

### LINKED ISSUE #4064: Using FSRS simulator after updating params (without saving) uses old memory states
If I update the FSRS parameters (by optimization or manually) and then use the FSRS simulator before saving the preset options, the simulator uses the memory states saved in the cards (i.e., the states generated from the previous parameters).

Possible solutions:
- If the parameters have been updated, ask the user to save the preset options when they try to use the simulator.
- If the parameters are not the same as the saved parameters, don't use the memory states stored in the cards. Rather, calculate the memory states on the fly (but don't save them to the card).

### PR DESCRIPTION
**Pull request by Luc-Mcgrady**
fixes #4064

This will prevent users from running the simulator after optimizing, before saving the preset.

### CODE REVIEW

File: ts/routes/deck-options/FsrsOptions.svelte [hunk 1]
```diff
@@ -53,6 +53,7 @@ License: GNU AGPL, version 3 or later; http://www.gnu.org/licenses/agpl.html
     let desiredRetentionFocused = false;
     let desiredRetentionEverFocused = false;
     let optimized = false;
+    const initialParmas = [...fsrsParams($config)];
```
Comment (user1823) [inline ts/routes/deck-options/FsrsOptions.svelte]: Typo: initialParams

File: ts/routes/deck-options/FsrsOptions.svelte [hunk 2]
```diff
@@ -338,6 +339,17 @@ License: GNU AGPL, version 3 or later; http://www.gnu.org/licenses/agpl.html
         state.save(UpdateDeckConfigsMode.COMPUTE_ALL_PARAMS);
     }
 
+    function showSimulatorModal(modal: Modal) {
+        if (
+            initialParmas.length === 0 ||
```
Comment (user1823) [inline ts/routes/deck-options/FsrsOptions.svelte]: If initial params are empty and current params are not, this will return `True`, which is not desired.

File: ftl/core/deck-config.ftl [hunk 3]
```diff
@@ -498,6 +498,7 @@ deck-config-desired-retention-below-optimal = Your desired retention is below op
 # cards that can be recalled or retrieved on a specific date.
 deck-config-fsrs-simulator-experimental = FSRS Simulator (Experimental)
 deck-config-fsrs-simulate-desired-retention-experimental = FSRS Desired Retention Simulator (Experimental)
+deck-config-fsrs-simulate-save-preset = After optimizing, please save your config before running the simulator.
```
Comment (user1823) [inline ftl/core/deck-config.ftl:501]:
```suggestion
deck-config-fsrs-simulate-save-preset = Please save the updated parameters before running the simulator.
```

**Review by user1823 — CHANGES_REQUESTED** [review]

File: ts/routes/deck-options/FsrsOptions.svelte (hunk 2 above)
Comment (Luc-Mcgrady) [reply ts/routes/deck-options/FsrsOptions.svelte]:
```suggestion
```

File: ftl/core/deck-config.ftl (hunk 3 above)
Comment (Luc-Mcgrady) [reply ftl/core/deck-config.ftl:501]: I think its better if we keep the focus on saving the config, as there is no way to save the parameters separately.

**Comment by dae** [comment]
Thanks!
