### PR TITLE
Fix editor width changing as tag completions shown

### LINKED ISSUE #3514: Editor width is changing as tag completions shown
Reported on https://forums.ankiweb.net/t/anki-24-10-beta/49989/251

### PR DESCRIPTION
**Pull request by abdnh**
Closes #3514

Related Svelte issue: https://github.com/sveltejs/svelte/issues/9777

### CODE REVIEW

**Comment by abdnh** [comment]
There's a formatting issue I'm not sure how to solve yet. Might be something in dprint-plugin-prettier.

File: ts/lib/components/Portal.svelte [hunk 1]
```diff
@@ -39,6 +39,7 @@ License: GNU AGPL, version 3 or later; http://www.gnu.org/licenses/agpl.html
 </script>
 
 {#if !target}
+    <!-- eslint-disable -->
```
Comment (abdnh) [inline ts/lib/components/Portal.svelte:42]: Required because apparently eslint-plugin-svelte doesn't fully support Svelte 5 yet.

**Comment by dae** [comment]
Great job on figuring this out - thanks Abdo!
