### PR TITLE
Fix infinite update loop in editor with invalid input HTML

### LINKED ISSUE #1740: Certain field content causes HTML editor to get stuck in infinite loop
As reported on https://forums.ankiweb.net/t/anki-2-1-50-beta-6-9-stable-release/18181/62

Appears to have been introduced in 16e9e56ad8a52cf075b90f54e846c223736252cd

Adding a print statement to the top of removeProhibitedTags() shows that the HTML is oscillating between two states:

```
JS info /_anki/js/browser_editor.js:73476 html: n. <m. 1=""> jmd., der stiehlt bzw. gestohlen hat; einen ~ bestrafen, ertappen, fangen, festnehmen; haltet den ~! (Alarmruf, wenn man einen Dieb auf frischer Tat ertappt) [<ahd. diob,="" engl.="" thief,="" got.="" þiufs,="" þiubis;="" zu="" idg.="" *teup-="" sich="" niederkauern,="" hocken="" (um="" sich="" verbergen)]<="" body=""></ahd.></m.>
JS info /_anki/js/browser_editor.js:73476 html: n. <m. 1=""> jmd., der stiehlt bzw. gestohlen hat; einen ~ bestrafen, ertappen, fangen, festnehmen; haltet den ~! (Alarmruf, wenn man einen Dieb auf frischer Tat ertappt) [</m.>
```

### PR DESCRIPTION
**Pull request by hgiesel**
Closes #1740.

The issue was caused by invalid HTML, which is changed by parsing and serializing it again.
The `RichTextInput` did parse+serialize incoming HTML, while the `PlainTextInput` did not. This caused the loop. This could only happen when writing directly into the db, bypassing the editor.

Most of the PR is refactoring.

### CODE REVIEW

File: ts/editor/plain-text-input/PlainTextInput.svelte [hunk 1]
```diff
@@ -49,79 +48,83 @@ License: GNU AGPL, version 3 or later; http://www.gnu.org/licenses/agpl.html
...
-            unsubscribeFromEditingArea();
-            unsubscribeToEditingArea();
-        };
+        return singleCallback(
+            content.subscribe((html: string): void =>
+                /* We call `removeProhibitedTags` here, because content might
+                 * have been changed outside the editor, and we need to parse
+                 * it to get the "neutral" value. Otherwise, there might be
+                 * conflicts with other editing inputs */
+                code.set(removeProhibitedTags(storedToUndecorated(html))),
```
Comment (hgiesel) [inline ts/editor/plain-text-input/PlainTextInput.svelte:122]: This is what fixes the bug.

**Comment by dae** [comment]
The CI server needed some disk space freeing up :-)

Thanks for looking into this Henrik; the fix seems to work well.

I'm not very familiar with this part of the code, so I'm assuming that by including the refactoring in this PR, it was either required as part of the fix, or the changes are unlikely to introduce regressions. I get a bit nervous about changes near a release, so it might be nice to separate out non-essential changes into separate PRs around release time. :-)
