### PR TITLE
Refactor plain/rich text input toggling code; fix focus loss

### LINKED ISSUE #2476: Focus lost when closing HTML editor
https://forums.ankiweb.net/t/enhancement-focus-on-a-field-after-closing-html-editor/29390

### PR DESCRIPTION
**Pull request by hikaru-y**
Fixes #2476

The main purpose of this refactoring is to move the focus processing inside the reactive statements so that polling using `requestAnimationFrame` is no longer necessary.

### CODE REVIEW

File: ts/editor/helpers.ts [hunk 1]
```diff
@@ -23,14 +20,20 @@ export function withFontColor(
...
+
+    constructor() {
+        this.flag = false;
+    }
+
+    setFlag(on: boolean): void {
+        this.flag = on;
+    }
+
+    check(): boolean {
```
Comment (dae) [inline ts/editor/helpers.ts:34]:
```suggestion
    /// Resets the flag to false and returns the previous value.
    checkAndReset(): boolean {
```

**Review by dae — COMMENTED** [review]
Thanks as always for your work on the TS code Hikaru. Just a minor suggestion for clarity:

**Comment by dae** [comment]
Thanks Hikaru.
