### PR TITLE
Fix maybe_coalesce_note_undo_entry()

### LINKED ISSUE #2974: maybe_coalesce_note_undo_entry() is not working
It's failing because the current and previous ops store [note change, collection modified], not just [note change], so we can't just use .last().

https://forums.ankiweb.net/t/feature-request-undo-update-note/40374

### PR DESCRIPTION
**Pull request by abdnh**
Closes #2974

### CODE REVIEW

File: rslib/src/notes/undo.rs [hunk 1]
```diff
@@ -64,20 +67,47 @@ impl Collection {
...
+            _ => false,
+        };
+
+        let changes_to_pop = current_op
+            .changes
+            .iter()
+            .rev()
+            .take_while(is_col_modified_change)
+            .collect_vec()
+            .len()
```
Comment (dae) [inline rslib/src/notes/undo.rs:92]: This can be done more efficiently with .count() instead of .collect_vec().len()

File: rslib/src/notes/undo.rs [hunk 2]
```diff
@@ -64,20 +67,47 @@ impl Collection {
...
+            + 1;
+        let current_op_change = current_op
+            .changes
+            .iter()
+            .rev()
+            .find(|c| !is_col_modified_change(c));
```
Comment (dae) [inline rslib/src/notes/undo.rs:98]: While very unlikely, this could theoretically drop the entire undo entry if the operation changed multiple notes, and the last change of the two operations was for the same note. Perhaps it would make more sense to compare .first() instead? This coalescing is only intended to happen in the single-note update case.

Comment (abdnh) [reply rslib/src/notes/undo.rs]: Hmm, will it drop the entire entry though? The code is only popping UndoableCollectionChange::Modified changes and a single UndoableNoteChange::Updated at the end of the vec. I changed that anyway.

Comment (dae) [reply rslib/src/notes/undo.rs]: Sorry, you're right - I misread the code. Thinking about it more, it might make the code a bit simpler to explicitly match/clear the entire list of changes. I've pushed a tweak that does this - does it look ok to you? Apologies for the changing requirements :-)

Comment (abdnh) [reply rslib/src/notes/undo.rs]: Looking better to me!
